on:
    push:
      branches:
        - master2
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: 'Log in to docker Hub'
          run: docker login --username ${{ secrets.DOCKERUSERNAME}} --password ${{ secrets.DOCKERTOKEN}} 
        - name: 'Building docker image'
          run: docker build -t ${{ secrets.DOCKERUSERNAME}}/myimage .
        - name: 'Building docker image'
          run: docker push ${{ secrets.DOCKERUSERNAME}}/myimage

