on:
    push:
      branches:
        - master2
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: 'Log in to docker Hub'
          run: docker login --username ahmdes --password dckr_pat_sy1haJgBxA5n29lxHLah9mDcZVI

